spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CupFlowERP
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        type:
          preferred_boolean_jdbc_type: BOOLEAN
        jdbc:
          time_zone: UTC

  jackson:
    default-property-inclusion: non_null

server:
  port: 8080

app:
  jwt:
    secret: 4k2nL8xQmP7vR3sT9yA1bC6dE0fG5hJ8mN2pQ7rS4uV9xY3zW6aB1cD8eF2gH7jK
    expirationMs: 86400000

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR

kind: Application