package com.cupflow.CupFlow_ERP.order;

public enum OrderStage {
    ORDER_RECEIVED,
    RAW_MATERIAL_ISSUED,
    SHEET_MAKING_IN_PROGRESS,
    SHEET_READY,
    CUP_MOLDING_IN_PROGRESS,
    CUPS_READY_FOR_PRINTING,
    PRINTING_IN_PROGRESS,
    READY_TO_DISPATCH,
    DISPATCHED
}
